### ISSUE TITLE
error with nodebb 0.6.x

### ISSUE THREAD

**Issue by laudney** [NodeBB/nodebb-plugin-featured-threads#6]
error: TypeError: Cannot call method 'push' of undefined
    at Object.Plugin.addThreadTools [as method] (/home/reddcoin/reddcointalk.org/node_modules/nodebb-plugin-featured-threads/library.js:72:14)
    at /home/reddcoin/reddcointalk.org/src/plugins/hooks.js:89:12
    at /home/reddcoin/reddcointalk.org/node_modules/async/lib/async.js:272:13
    at iterate (/home/reddcoin/reddcointalk.org/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/home/reddcoin/reddcointalk.org/node_modules/async/lib/async.js:165:9)
    at Object.async.reduce (/home/reddcoin/reddcointalk.org/node_modules/async/lib/async.js:271:15)
    at fireFilterHook (/home/reddcoin/reddcointalk.org/src/plugins/hooks.js:81:9)
    at Plugins.fireHook (/home/reddcoin/reddcointalk.org/src/plugins/hooks.js:66:5)
    at Object.threadTools (/home/reddcoin/reddcointalk.org/node_modules/async/lib/async.js:656:23)
    at /home/reddcoin/reddcointalk.org/node_modules/async/lib/async.js:583:25
[cluster] Child Process (2148) has exited (code: 1, signal: null)

**Comment by barisusakli** [comment]
0.1.1 for nodebb 0.6.x
0.1.2 for nodebb 0.7.x

I think pluign needs compatibility field in plugin.json

**Comment by laudney** [comment]
It indeed needs compatibility field in plugin.json.

**Comment by psychobunny** [comment]
https://github.com/NodeBB/nodebb-plugin-featured-threads/pull/8
